-- root 계정에서
create database memberdb;

grant all privileges on memberdb.* to ohgiraffers@'%';
--
USE memberdb;

DROP TABLE IF EXISTS `MEMBER_INFO`;
CREATE TABLE IF NOT EXISTS `MEMBER_INFO`
(
    `MEMBER_CODE` MEDIUMINT NOT NULL AUTO_INCREMENT COMMENT '회원코드',
    `MEMBER_NAME` VARCHAR(50) NOT NULL COMMENT '회원이름',
    `BIRTH_DATE` VARCHAR(8) COMMENT '생년월일',
    `DETAIL_INFO` VARCHAR(500) COMMENT '상세정보',
    `CONTACT` VARCHAR(50) COMMENT '연락처',
    `ACTIVE_STATUS` VARCHAR(1) NOT NULL COMMENT '활동상태',
    PRIMARY KEY ( `MEMBER_CODE` )
)
    COMMENT = '회원정보';

INSERT INTO MEMBER_INFO (MEMBER_NAME,BIRTH_DATE,DETAIL_INFO,CONTACT,ACTIVE_STATUS) VALUES
    ('홍길동','88/10/12','서울시','010-1234-5677','Y');
INSERT INTO MEMBER_INFO (MEMBER_NAME,BIRTH_DATE,DETAIL_INFO,CONTACT,ACTIVE_STATUS) VALUES
    ('유관순','98/11/12','부산시','010-1414-5622','Y');
INSERT INTO MEMBER_INFO (MEMBER_NAME,BIRTH_DATE,DETAIL_INFO,CONTACT,ACTIVE_STATUS) VALUES
    ('신사임당','87/0/12','서울시','010-1412-5117','Y');
INSERT INTO MEMBER_INFO (MEMBER_NAME,BIRTH_DATE,DETAIL_INFO,CONTACT,ACTIVE_STATUS) VALUES
    ('강감찬','88/02/22','광주시','010-1451-5691','Y');
INSERT INTO MEMBER_INFO (MEMBER_NAME,BIRTH_DATE,DETAIL_INFO,CONTACT,ACTIVE_STATUS) VALUES
    ('윤봉길','90/03/24','대전시','010-1122-5687','Y');
INSERT INTO MEMBER_INFO (MEMBER_NAME,BIRTH_DATE,DETAIL_INFO,CONTACT,ACTIVE_STATUS) VALUES
    ('이순신','84/03/31','마산시','010-1331-5117','Y');
COMMIT;